title: Jonathan Strong
description: "A blog about infosec"
author:
  name: "Jonathan Strong"
  email: "someone@somewebsite.somedomain"
  url: "https://jonathanstrong.org"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-target-blank 

# Custom variables
owner : "Jonathan Strong"
year : "2022"
timezone: Europe/London


theme: jekyll-theme-hacker
