name: HawkScan
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
permissions:
  contents: read
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@29a62fe1e926ea50ac87a1b64efc59b82ffd5b7d # v2.2.0
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
